travis:
  secure:
    BINSTAR_TOKEN: dq6lcLaEgTwl4gUzCxtnT9OH12UdalaQ/0Ljjl0KP2jThuzRWxRWsUIk/ubDLRFDZuQQJEv3kjwozZht1XMWhn4LPvPHCCcop9wzuDPbIcinzOggO9w9znB1wNsPFFCofZEdhqNWmny/NxSC9gnTGL/9QiOZl1GEY2YS0cxhiWICPQgJkc2IBHWUBcvghcwfLpKTCq029sK57QNe0kDz/XzMaDX/bJm3+mpyZOpyozt0Bs3j1tH/M2BfDPuFcvyHCramMNVtEyiBUCnV63MyEsj/czEiaFmh4Gj3GngtUPc51T49l3KsDnXdJ4Y2odBfDGInOTofU4pmVMHIs+ZPk/WFAi3HYjpa68/gHAZoDGK8zzIcCprZdis63S5HuT6pwbCXUB813EU5vab9QkViGTC/Ru1tc+ui7mQKk6zpXXqsrImgzJC6G0SGolP7A5oXeftlfDrYJnhCM8KMAs4gmeW9SYBJUF3a6JrHnWExGIh4slaLB7lQIgXgXcNbBLE7dTSNKunZs0kRuDmBqa1IMrIXOxR49aVmvZZPT/kKnIr17ey8eWxmUsVKBFC3Tvuk+PD+R8rmR+v20VLMjEHl/25BFyUOcKvoAk5h4n8xF0C9Z86sZ6L+W1whqhhFsenEE9yyC//NgPqMvxwDO3OIoisfO0FMjwe4vsJVHyJ8yJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
