travis:
  secure:
    BINSTAR_TOKEN: j5KcRZkaxwlpcLFhn5d09ovJqhaOhPED6SSx669w0CZpRzbiyiQVM/DhTMSumOu0N8ntlxdkfNp+pdjmL40LRzvU1EXiQRX1laUGVl2uKODWkkzaphNF8vz9FEGm+MLEdaROwZKRTvXe/DU4MdutXMijXMNNYv2dywXLC1vF1TkfZvC+Qqydgcjxm2iHD5xz+3HhZmyeQHiTMKtbVpxAqGAocs1SDtDa3hIkZ5qZ1C+vHMOJJ9+E4qGqWx6e88Z+liHM5VZMdOk/8I1K2hgoMuvgXjLsu+nwv/x3kchZsIQGS+ecvfyr3P3dZWNA38Nu8FSGKRspesECcpl5JQTrCpfhIDu+y/+n/OsTgWWqJCaMTBLVeg5p3R+dJAFsayngurThqvt2cQlVjJrasJGrbamTw1oeVrV7Pa91GlyukhFl0k6WUQ1psgfNmGHxVRyutNrgwGGXoX6qNsgDc+y6PieTUXE+j9vwi0BXv5WZ/hV64Gd7O/tnEskvmvAHHHJ3lYWH9VsVlpn1sbWE+7WK5pUeJhwxeE93K3/dHld3xLnqmgX94AjbPAxez92Q3usoQWoae5+74NT8Te/JtXjHijr5+y0vi0Jxfz3eWL3e8BDcRFc+YUmt/Kxk4KehsS+aq2F4U4MNCWDzKpubPn4qdlpxMyZBtD1QyhSlUd6l8Xs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
